Document: xanalysis
Title: Debian xanalysis Manual
Author: <insert document author here>
Abstract: This manual describes what xanalysis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xanalysis/xanalysis.sgml.gz

Format: postscript
Files: /usr/share/doc/xanalysis/xanalysis.ps.gz

Format: text
Files: /usr/share/doc/xanalysis/xanalysis.text.gz

Format: HTML
Index: /usr/share/doc/xanalysis/html/index.html
Files: /usr/share/doc/xanalysis/html/*.html
